import type { Metadata } from 'next';
import '../styles/global.scss';
import Toolbar from '@/UI/Toolbar/Toolbar';
import { montserrat } from '../../fontConfig';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Toolbar />
        <div>{children}</div>
        {/*<FooterBottom />*/}
        {/*/!*<Footer />*!/*/}
      </body>
    </html>
  );
}
