import type { Metadata } from 'next';
import Toolbar from '@/UI/Toolbar/Toolbar';
import { montserrat } from '../../fontConfig';
import '../styles/global.scss';
import StoreProvider from '@/app/StoreProvider';

export const metadata: Metadata = {
  title: 'umbrella agency',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={montserrat.className}>
          <Toolbar background="inherit" color="$primary-10" />
          <div>{children}</div>
          {/*<FooterBottom />*/}
          {/*/!*<Footer />*!/*/}
        </body>
      </html>
    </StoreProvider>
  );
}
